apiVersion: apps/v1
kind: Deployment
metadata:
    name: super-deployment
    labels:
      app: super
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super
  template:
    metadata:
      labels:
        app: super
    spec:
      containers:
        - name: superset
          image: haim77420/superset:1.1
          env:
            - name: SUPERSET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: SUPERSET_SECRET_KEY
            - name: COMPOSE_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: COMPOSE_PROJECT_NAME
            - name: DEV_MODE
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: DEV_MODE
            - name: DATABASE_DB
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: DATABASE_DB
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: DATABASE_HOST
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: DATABASE_USER
            - name: EXAMPLES_DB
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: EXAMPLES_DB
            - name: EXAMPLES_HOST
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: EXAMPLES_HOST
            - name: EXAMPLES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: EXAMPLES_PASSWORD
            - name: EXAMPLES_PORT
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: EXAMPLES_PORT
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: DATABASE_PORT
            - name: DATABASE_DIALECT
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: DATABASE_DIALECT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: REDIS_PORT
            - name: FLASK_DEBUG
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: FLASK_DEBUG
            - name: SUPERSET_APP_ROOT
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: SUPERSET_APP_ROOT
            - name: SUPERSET_ENV
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: SUPERSET_ENV
            - name: SUPERSET_LOAD_EXAMPLES
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: SUPERSET_LOAD_EXAMPLES
            - name: CYPRESS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: CYPRESS_CONFIG
            - name: SUPERSET_PORT
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: SUPERSET_PORT
            - name: MAPBOX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: MAPBOX_API_KEY
            - name: ENABLE_PLAYWRIGHT
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: ENABLE_PLAYWRIGHT
            - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
            - name: BUILD_SUPERSET_FRONTEND_IN_DOCKER
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: BUILD_SUPERSET_FRONTEND_IN_DOCKER
            - name: SUPERSET_LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: superset-secrets
                  key: SUPERSET_LOG_LEVEL


          command: [ "sh", "-c" ]
          args:
              - |
                superset db upgrade &&
                superset fab create-admin \
                  --username admin \
                  --firstname Superset \
                  --lastname Admin \
                  --email admin@example.com \
                  --password admin &&
                superset init &&
                superset run -h 0.0.0.0 -p 8088

          ports:
            - containerPort: 8088

---

apiVersion: v1
kind: Service
metadata:
  name: superset-service
spec:
  selector:
    app: super
  ports:
  - name: http
    port: 8088

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-deployment
    labels:
      app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
    labels:
      app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: db
          image: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: adminer-deployment
    labels:
      app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
      ports:
        - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  selector:
    app: adminer
  ports:
  - name: http
    port: 8080

