apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-service-manager
  namespace: secure-app
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list", "create", "delete", "update"]