version: '3.8'
services:
  app:
    image: haim77420/flask:6
    env_file:
     - .env
    environment:
      - CACHE_TYPE=$CACHE_TYPE
      - CACHE_REDIS_HOST=$CACHE_REDIS_HOST
      - CACHE_REDIS_PORT=$CACHE_REDIS_PORT
      - CACHE_REDIS_DB=$CACHE_REDIS_DB
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine

