apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: multi-tier-app
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    
