apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-deployment
  namespace: multi-tier-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-tier-app
  template:
    metadata:
      labels:
        app: multi-tier-app
    spec:
      containers:
      - name: flask-redis
        image: haim77420/flask-redis:0.1
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: REDIS_PORT
          - name: REDIS_DB
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: REDIS_DB
          - name: REDIS_USER
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: REDIS_USER
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: REDIS_PASSWORD
        ports:
        - containerPort: 8000