apiVersion: v1
kind: Service
metadata:
  name: flask-redis-service
  namespace: multi-tier-app
spec:
  selector:
    app: multi-tier-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort