apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mysql-deployment
  namespace: fullstack-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-mysql
  template:
    metadata:
      labels:
        app: flask-mysql
    spec:
      containers:
      - name: flask-mysql
        image: haim77420/flask-mysql:0.2
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: AUTH_PLUGIN
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: AUTH_PLUGIN
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 8000