apiVersion: v1
kind: Service
metadata:
  name: flask-mysql-service
  namespace: fullstack-app
spec:
  selector:
    app: flask-mysql
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort