apiVersion: v1
kind: Namespace
metadata:
  name: development

---

apiVersion: v1
kind: Namespace
metadata:
  name: production

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: development
  labels:
    app: nginx
    exercise: PartII
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      exercise: PartII
  template:
    metadata:
      labels:
        app: nginx
        exercise: PartII
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: production
  labels:
    app: nginx
    exercise: PartII
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      exercise: PartII
  template:
    metadata:
      labels:
        app: nginx
        exercise: PartII
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
